.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "DPKG\-RECONFIGURE\-NONINTERACTIVE" "8" "January 2020" "helper-scripts" "helper-scripts Manual"
.SH "NAME"
\fBdpkg\-reconfigure\-noninteractive\fR \- wrapper to run \fBdpkg\-reconfigure\fR non\-interactively
.SH "SYNOPSIS"
\fBdpkg\-reconfigure\-noninteractive\fR [args\|\.\|\.\|\.]
.SH "DESCRIPTION"
Simple wrapper that sets environment variables for non\-interactive use, prevents daemons from restarting during reconfiguration, then forwards all arguments to \fBdpkg\-reconfigure\fR\. No debconf prompts will appear during reconfiguration\.
.SH "EXAMPLES"
\fBsudo dpkg\-reconfigure\-noninteractive tzdata\fR
.P
\fBsudo dpkg\-reconfigure\-noninteractive keyboard\-configuration\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
